import 'dart:io';

/// The fingerprint of `test/fixtures/server_identity_cert.pem`, independently
/// generated by the Go server's own `securetransport.BuildTLSConfig` (not
/// hand-crafted), so tests here exercise real cross-language interop
/// between the Go and Dart halves of ADR-008/ADR-009.
const String fixtureServerFingerprint = '98f40c81c8b146bfc0ee319c95ded5acf0be436d9e0d1e2643706809de856a56';

Future<HttpServer> startFixtureServer(void Function(HttpRequest request) handler) async {
  final context = SecurityContext()
    ..useCertificateChain('test/fixtures/server_identity_cert.pem')
    ..usePrivateKey('test/fixtures/server_identity_key.pem');
  final server = await HttpServer.bindSecure(InternetAddress.loopbackIPv4, 0, context);
  server.listen(handler);
  return server;
}
